version: "3.8"

services:
  landingpage:
    image: nginx:alpine
    container_name: landingpage
    restart: unless-stopped
    ports:
      - "100:80"
    command: >
      /bin/sh -c "
      apk add --no-cache git &&
      rm -rf /usr/share/nginx/html/* &&
      git clone https://github.com/iqballfarhan/LandingPageMiniServer.git /tmp/repo &&
      cp -r /tmp/repo/stack/html/* /usr/share/nginx/html/ &&
      rm -rf /tmp/repo &&
      nginx -g 'daemon off;'
      "
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
