version: "3.8"

services:
  landingpage:
    image: nginx:alpine
    container_name: landingpage
    restart: unless-stopped
    ports:
      - "100:80"
    command: >
      sh -c "
      mkdir -p /usr/share/nginx/html/css /usr/share/nginx/html/js &&
      wget -q -O /etc/nginx/conf.d/default.conf https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/nginx.conf || echo 'nginx config gagal' &&
      wget -q -O /usr/share/nginx/html/index.html https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/index.html || echo '<h1>index gagal</h1>' > /usr/share/nginx/html/index.html &&
      wget -q -O /usr/share/nginx/html/login.html https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/login.html || echo '<h1>login gagal</h1>' > /usr/share/nginx/html/login.html &&
      wget -q -O /usr/share/nginx/html/index-new.html https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/index-new.html || true &&
      wget -q -O /usr/share/nginx/html/css/index-old.css https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/css/index-old.css || true &&
      wget -q -O /usr/share/nginx/html/css/index-new.css https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/css/index-new.css || true &&
      wget -q -O /usr/share/nginx/html/css/login.css https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/css/login.css || true &&
      wget -q -O /usr/share/nginx/html/js/index-old.js https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/js/index-old.js || true &&
      wget -q -O /usr/share/nginx/html/js/index-new.js https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/js/index-new.js || true &&
      wget -q -O /usr/share/nginx/html/js/login.js https://raw.githubusercontent.com/iqballfarhan/LandingPageMiniServer/main/stack/html/js/login.js || true &&
      nginx -t &&
      exec nginx -g 'daemon off;'
      "
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
