version: "3.8"

services:
  landingpage:
    image: nginx:latest
    container_name: landingpage
    restart: unless-stopped
    ports:
      - "100:80"         # expose host:100 -> container:80
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
